// Bytecode length of Inferno's hot functions per variant (d8 --print-bytecode on the micro bundle).
// TurboFan inlines functions up to 460 bytes of bytecode, and their size counts against the caller's
// cumulative inlining budget: a change must not make them longer than in the baseline (first
// variant), or callers such as the keyed-children loop stop inlining them.
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { buildOptionMatrix } from '../lib/options.ts';
import { CHROMIUM_SRC } from '../lib/paths.ts';
import { run, table } from '../lib/util.ts';
import { buildMicroBundle } from '../micro/build.ts';
import { ensureVariant } from '../variants/build.ts';
import { parseVariantList } from '../variants/spec.ts';

const INLINE_LIMIT = 460;

const WATCH = [
  'patch',
  'patchElement',
  'patchFragment',
  'patchChildren',
  'patchFunctionalComponent',
  'patchClassComponent',
  'patchKeyedChildren',
  'patchKeyedChildrenComplex',
  'patchNonKeyedChildren',
  'replaceWithNewNode',
  'mount',
  'mountElement',
  'mountFragment',
  'mountArrayChildren',
  'mountClassComponent',
  'mountFunctionalComponent',
  'mountClassComponentCallbacks',
  'mountFunctionalComponentCallbacks',
  'unmount',
  'remove',
  'removeVNodeDOM',
  'clearVNodeDOM',
  'findDOMFromVNode',
  'moveVNodeDOM',
  'renderInternal',
];

// Cases that between them execute every watched function (bytecode is printed when a function is compiled)
const CASES = [
  'fuzz/5',
  'fuzz/9',
  'keyed/fc/reverse',
  'keyed/el/shuffle',
  'mount/components-1k',
  'unmount/components-1k',
  'jfb/keyed/04_select1k',
  'state/setState-leaf-of-100',
];

function parseLengths(out: string, into: Map<string, number>): void {
  const re = /\[generated bytecode for function: ([^\s(]+)[^\]]*\]\s*\n\s*Bytecode length: (\d+)/g;
  for (let m = re.exec(out); m; m = re.exec(out)) {
    // Rollup renames clashing top-level names to name$1
    const name = m[1].replace(/\$\d+$/, '');
    const length = Number(m[2]);
    into.set(name, Math.max(into.get(name) ?? 0, length));
  }
}

export default async function bytecode(argv: string[]): Promise<number> {
  const { values } = parseArgs({
    args: argv,
    options: {
      variants: { type: 'string' },
      d8: { type: 'string' },
      preload: { type: 'string' },
    },
  });
  const d8 = values.d8 ?? join(CHROMIUM_SRC, 'out/InfernoProf/d8');
  if (!existsSync(d8)) {
    throw new Error(`d8 not found at ${d8}: build it with \`pnpm bench chromium build\` or pass --d8 <path>`);
  }
  const specs = parseVariantList(values.variants);
  const preload = values.preload ? values.preload.split(',').map((m) => m.trim()).filter(Boolean) : [];
  const [options] = buildOptionMatrix(undefined, 'off');

  const lengths: Map<string, number>[] = [];
  for (const spec of specs) {
    const variant = await ensureVariant(spec);
    const bundle = await buildMicroBundle(variant, options, 'd8', preload);
    const found = new Map<string, number>();
    for (const c of CASES) {
      const res = await run(d8, ['--print-bytecode', bundle.file, '--', c, '3', '1'], { allowFail: true });
      parseLengths(res.stdout, found);
    }
    lengths.push(found);
  }

  let grew = 0;
  const rows = WATCH.map((name) => {
    const base = lengths[0].get(name);
    const cells: string[] = [name, base === undefined ? '-' : String(base)];
    for (const found of lengths.slice(1)) {
      const len = found.get(name);
      if (len === undefined || base === undefined) {
        cells.push(len === undefined ? '-' : String(len));
        continue;
      }
      const inlinable = base <= INLINE_LIMIT || len <= INLINE_LIMIT;
      const flag = len > base && inlinable ? ' !' : '';
      if (flag) grew++;
      cells.push(`${len} (${len - base >= 0 ? '+' : ''}${len - base})${flag}`);
    }
    return cells;
  });
  console.log(table(['function', ...specs.map((s) => s.id)], rows));
  console.log(`\n! = inlinable (<= ${INLINE_LIMIT} bytes) and longer than ${specs[0].id}`);
  return grew > 0 ? 1 : 0;
}
