packages:
  - packages/*
  - fixtures/*
  - demo/*
  - benchmarks/*
  - hacker-news

linkWorkspacePackages: true
sharedWorkspaceLockfile: true
strictPeerDependencies: false

overrides:
  webdriver: 9.27.0
  webdriverio: 9.27.0

allowBuilds:
  '@parcel/watcher@2.5.6': true
  '@swc/core@1.15.24': true
  edgedriver@6.3.0: true
  esbuild: true
  geckodriver@6.1.0: true
  lmdb@2.8.5: true
  msgpackr-extract@3.0.3: true
  unrs-resolver@1.12.2: true
