let rootListeners = {};

export default {

    blur: [],
    change: [],
    click: [],
    contextmenu: [],
    copy: [],
    cut: [],
    dblclick: [],
    drag: [],
    dragend: [],
    dragenter: [],
    dragexit: [],
    dragleave: [],
    dragover: [],
    dragstart: [],
    drop: [],
    error: [],
    focus: [],
    input: [],
    invalid: [],
    keydown: [],
    keypress: [],
    keyup: [],
    load: [],
    mousedown: [],
    mouseenter: [],
    mouseleave: [],
    mousemove: [],
    mouseout: [],
    mouseover: [],
    mouseup: [],
    paste: [],
    reset: [],
    scroll: [],
    submit: [],
    touchcancel: [],
    touchend: [],
    touchmove: [],
    touchstart: [],
    wheel: []
};