import checkBitmask from './checkBitmask';

const IS_SVG = 0x15;
const IS_MATHML = 0x20;

// DOM Element list here
const DOMElements = {

    a: IS_SVG,
    altGlyph: IS_SVG,
    altGlyphDef: IS_SVG,
    altGlyphItem: IS_SVG,
    animate: IS_SVG,
    animateColor: IS_SVG,
    animateMotion: IS_SVG,
    animateTransform: IS_SVG,
    circle: IS_SVG,
    clipPath: IS_SVG,
    'color-profile': IS_SVG,
    cursor: IS_SVG,
    defs: IS_SVG,
    desc: IS_SVG,
    ellipse: IS_SVG,
    feBlend: IS_SVG,
    feColorMatrix: IS_SVG,
    feComponentTransfer: IS_SVG,
    feComposite: IS_SVG,
    feConvolveMatrix: IS_SVG,
    feDiffuseLighting: IS_SVG,
    feDisplacementMap: IS_SVG,
    feDistantLight: IS_SVG,
    feFlood: IS_SVG,
    feFuncA: IS_SVG,
    feFuncB: IS_SVG,
    feFuncG: IS_SVG,
    feFuncR: IS_SVG,
    feGaussianBlur: IS_SVG,
    feImage: IS_SVG,
    feMerge: IS_SVG,
    feMergeNode: IS_SVG,
    feMorphology: IS_SVG,
    feOffset: IS_SVG,
    fePointLight: IS_SVG,
    feSpecularLighting: IS_SVG,
    feSpotLight: IS_SVG,
    feTile: IS_SVG,
    feTurbulence: IS_SVG,
    filter: IS_SVG,
    font: IS_SVG,
    'font-face': IS_SVG,
    'font-face-format': IS_SVG,
    'font-face-name': IS_SVG,
    'font-face-src': IS_SVG,
    'font-face-uri': IS_SVG,
    foreignObject: IS_SVG,
    g: IS_SVG,
    glyph: IS_SVG,
    glyphRef: IS_SVG,
    hkern: IS_SVG,
    image: IS_SVG,
    line: IS_SVG,
    linearGradient: IS_SVG,
    marker: IS_SVG,
    mask: IS_SVG,
    metadata: IS_SVG,
    math: IS_MATHML,
    maction: IS_MATHML,
    maligngroup: IS_MATHML,
    malignmark: IS_MATHML,
    menclose: IS_MATHML,
    merror: IS_MATHML,
    mfenced: IS_MATHML,
    mfrac: IS_MATHML,
    mglyph: IS_MATHML,
    mi: IS_MATHML,
    mlabeledtr: IS_MATHML,
    mlongdiv: IS_MATHML,
    mmultiscripts: IS_MATHML,
    mn: IS_MATHML,
    mo: IS_MATHML,
    mover: IS_MATHML,
    mpadded: IS_MATHML,
    mphantom: IS_MATHML,
    mroot: IS_MATHML,
    mrow: IS_MATHML,
    ms: IS_MATHML,
    mscarries: IS_MATHML,
    mscarry: IS_MATHML,
    msgroup: IS_MATHML,
    msline: IS_MATHML,
    mspace: IS_MATHML,
    msqrt: IS_MATHML,
    msrow: IS_MATHML,
    mstack: IS_MATHML,
    mstyle: IS_MATHML,
    msub: IS_MATHML,
    msup: IS_MATHML,
    msubsup: IS_MATHML,
    'missing-glyph': IS_SVG,
    mpath: IS_SVG,
    path: IS_SVG,
    pattern: IS_SVG,
    polygon: IS_SVG,
    polyline: IS_SVG,
    radialGradient: IS_SVG,
    rect: IS_SVG,
    script: IS_SVG,
    set: IS_SVG,
    stop: IS_SVG,
    style: IS_SVG,
    svg: IS_SVG,
    switch: IS_SVG,
    symbol: IS_SVG,
    text: IS_SVG,
    textPath: IS_SVG,
    title: IS_SVG,
    tref: IS_SVG,
    tspan: IS_SVG,
    use: IS_SVG,
    view: IS_SVG,
    vkern: IS_SVG
}

let DOMElementContainer = {};

for (let element in DOMElements) {

    let elementConfig = DOMElements[element];

    let elementInfo = {

        isSVG: checkBitmask(elementConfig, IS_SVG),
        isMathML: checkBitmask(elementConfig, IS_MATHML),
    }

    DOMElementContainer[element] = elementInfo;
}

export default DOMElementContainer;