import DOMAttributeNamespaces from './DOMAttributeNamespaces';
import DOMAttributeNames from './DOMAttributeNames';
import DOMasks from './DOMasks';
import checkMask from './checkMask';

let DOMPropertyNames = {};

const {
    MUST_USE_PROPERTY,
    IS_EDGE_CASE,
    HAS_BOOLEAN_VALUE,
    HAS_NUMERIC_VALUE,
    HAS_POSITIVE_NUMERIC_VALUE

} = DOMasks;

let DOMPropertyContainer = {};

const DOMProperties = {
    /**
     * Standard Properties
     */
    accept: null,
    acceptCharset: null,
    accessKey: null,
    action: null,
    allowFullScreen: HAS_BOOLEAN_VALUE,
    allowTransparency: null,
    alt: null,
    async: HAS_BOOLEAN_VALUE,
    autoComplete: null,
    autoFocus: HAS_BOOLEAN_VALUE,
    autoPlay: HAS_BOOLEAN_VALUE,
    capture: HAS_BOOLEAN_VALUE,
    cellPadding: null,
    cellSpacing: null,
    charSet: null,
    challenge: null,
    checked: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
    classID: null,
    className: null,
    cols: HAS_POSITIVE_NUMERIC_VALUE,
    colSpan: null,
    content: null,
    contentEditable: null,
    contextMenu: null,
    controls: HAS_BOOLEAN_VALUE,
    coords: null,
    crossOrigin: null,
    currentTime: MUST_USE_PROPERTY | HAS_POSITIVE_NUMERIC_VALUE,
    data: null, // For `<object />` acts as `src`.
    dateTime: null,
    default: HAS_BOOLEAN_VALUE,
    defer: HAS_BOOLEAN_VALUE,
    dir: null,
    disabled: HAS_BOOLEAN_VALUE,
    download: HAS_BOOLEAN_VALUE,
    draggable: null,
    enabled: HAS_BOOLEAN_VALUE,
    encType: null,
    form: null,
    formAction: null,
    formEncType: null,
    formMethod: null,
    formNoValidate: HAS_BOOLEAN_VALUE,
    formTarget: null,
    frameBorder: null,
    headers: null,
    height: null,
    hidden: HAS_BOOLEAN_VALUE,
    high: null,
    href: null,
    hrefLang: null,
    htmlFor: null,
    httpEquiv: null,
    icon: null,
    id: null,
    inputMode: null,
    integrity: null,
    is: null,
    keyParams: null,
    keyType: null,
    kind: null,
    label: null,
    lang: null,
    list: null,
    loop: HAS_BOOLEAN_VALUE,
    low: null,
    manifest: null,
    marginHeight: null,
    marginWidth: null,
    max: null,
    maxLength: null,
    media: null,
    mediaGroup: null,
    method: null,
    min: null,
    minLength: null,
    // Caution; `option.selected` is not updated if `select.multiple` is
    // disabled with `removeAttribute`.
    multiple: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
    muted: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
    name: null,
    noValidate: HAS_BOOLEAN_VALUE,
    open: HAS_BOOLEAN_VALUE,
    optimum: null,
    pattern: null,
    paused: MUST_USE_PROPERTY,
    placeholder: null,
    playbackRate: MUST_USE_PROPERTY | HAS_NUMERIC_VALUE,
    poster: null,
    preload: null,
    radioGroup: null,
    readOnly: HAS_BOOLEAN_VALUE,
    rel: null,
    required: HAS_BOOLEAN_VALUE,
    reversed: HAS_BOOLEAN_VALUE,
    role: null,
    rows: null,
    rowSpan: HAS_NUMERIC_VALUE,
    sandbox: null,
    scope: null,
    scoped: HAS_BOOLEAN_VALUE,
    scrolling: null,
    seamless: HAS_BOOLEAN_VALUE,
    selected: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
    shape: null,
    size: HAS_POSITIVE_NUMERIC_VALUE,
    sizes: null,
    span: HAS_POSITIVE_NUMERIC_VALUE,
    spellCheck: null,
    src: null,
    srcDoc: null,
    srcLang: MUST_USE_PROPERTY,
    srcObject: MUST_USE_PROPERTY,
    srcSet: null,
    start: HAS_NUMERIC_VALUE,
    step: null,
    style: null,
    summary: null,
    tabIndex: null,
    target: null,
    title: null,
    // Setting .type throws on non-<input> tags
    type: null,
    useMap: null,
    value: MUST_USE_PROPERTY | IS_EDGE_CASE,
    volume: MUST_USE_PROPERTY | HAS_POSITIVE_NUMERIC_VALUE,
    width: null,
    wmode: null,
    wrap: null,

    /**
     * RDFa Properties
     */
    about: null,
    datatype: null,
    inlist: null,
    prefix: null,
    // property is also supported for OpenGraph in meta tags.
    property: null,
    resource: null,
    typeof: null,
    vocab: null,

    /**
     * Non-standard Properties
     */
    // autoCapitalize and autoCorrect are supported in Mobile Safari for
    // keyboard hints.
    autoCapitalize: null,
    autoCorrect: null,
    // autoSave allows WebKit/Blink to persist values of input fields on page reloads
    autoSave: null,
    // color is for Safari mask-icon link
    color: null,
    // itemProp, itemScope, itemType are for
    // Microdata support. See http://schema.org/docs/gs.html
    itemProp: null,
    itemScope: HAS_BOOLEAN_VALUE,
    itemType: null,
    // itemID and itemRef are for Microdata support as well but
    // only specified in the the WHATWG spec document. See
    // https://html.spec.whatwg.org/multipage/microdata.html#microdata-dom-api
    itemID: null,
    itemRef: null,
    // results show looking glass icon and recent searches on input
    // search fields in WebKit/Blink
    results: null,
    // IE-only attribute that specifies security restrictions on an iframe
    // as an alternative to the sandbox attribute on IE<10
    security: null,
    // IE-only attribute that controls focus behavior
    unselectable: null,

    /*
     * SVG
     */

    accentHeight: null,
    accumulate: null,
    alignmentBaseline: null,
    alphabetic: null,
    amplitude: null,
    animate: null,
    arabicForm: null,
    ascent: null,
    attributeType: null,
    azimuth: null,
    baseFrequency: null,
    baseProfile: null,
    baselineShift: null,
    bbox: null,
    bias: null,
    by: null,
    calcMode: null,
    capHeight: null,
    'class': null,
    clip: null,
    clipPath: null,
    clipPathUnits: null,
    clipRule: null,
    colorInterpolation: null,
    colorInterpolationFilters: null,
    colorProfile: null,
    colorRendering: null,
    contentScriptType: null,
    contentStyleType: null,
    cursor: null,
    cx: null,
    cy: null,
    d: null,
    descent: null,
    diffuseConstant: null,
    direction: null,
    display: null,
    divisor: null,
    dominantBaseline: null,
    dur: null,
    dx: null,
    dy: null,
    edgeMode: null,
    elevation: null,
    enableBackground: null,
    end: null,
    exponent: null,
    externalResourcesRequired: null,
    feColorMatrix: null,
    feComposite: null,
    feGaussianBlur: null,
    feMorphology: null,
    feTile: null,
    fill: null,
    fillOpacity: null,
    fillRule: null,
    filter: null,
    filterRes: null,
    filterUnits: null,
    floodColor: null,
    floodOpacity: null,
    fontFamily: null,
    fontSize: null,
    fontSizeAdjust: null,
    fontStretch: null,
    fontStyle: null,
    fontVariant: null,
    fontWeight: null,
    format: null,
    from: null,
    fx: null,
    fy: null,
    g1: null,
    g2: null,
    glyphName: null,
    glyphOrientationHorizontal: null,
    glyphOrientationVertical: null,
    glyphRef: null,
    gradientTransform: null,
    gradientUnits: null,
    hanging: null,
    horizAdvX: null,
    horizOriginX: null,
    horizOriginY: null,
    ideographic: null,
    imageRendering: null,
    in2: null,
    'in': null,
    intercept: null,
    k1: null,
    k2: null,
    k3: null,
    k4: null,
    k: null,
    kernelMatrix: null,
    kernelUnitLength: null,
    kerning: null,
    keyPoints: null,
    keySplines: null,
    keyTimes: null,
    lengthAdjust: null,
    letterSpacing: null,
    lightingColor: null,
    limitingConeAngle: null,
    local: null,
    markerEnd: null,
    markerHeight: null,
    markerMid: null,
    markerStart: null,
    markerUnits: null,
    markerWidth: null,
    mask: null,
    maskContentUnits: null,
    maskUnits: null,
    mathematical: null,
    mode: null,
    numOctaves: null,
    offset: null,
    opacity: null,
    operator: null,
    order: null,
    orient: null,
    orientation: null,
    origin: null,
    overflow: null,
    overlinePosition: null,
    overlineThickness: null,
    panose1: null,
    path: null,
    pathLength: null,
    patternContentUnits: null,
    patternTransform: null,
    patternUnits: null,
    pointerEvents: null,
    points: null,
    pointsAtX: null,
    pointsAtY: null,
    pointsAtZ: null,
    preserveAlpha: null,
    preserveAspectRatio: null,
    primitiveUnits: null,
    r: null,
    radius: null,
    refX: null,
    refY: null,
    renderingIntent: null,
    repeatCount: null,
    repeatDur: null,
    requiredExtensions: null,
    restart: null,
    result: null,
    resize: MUST_USE_PROPERTY,
    rotate: null,
    rx: null,
    ry: null,
    scale: null,
    seed: null,
    shapeRendering: null,
    slope: null,
    spacing: null,
    specularConstant: null,
    specularExponent: null,
    spreadMethod: null,
    startOffset: null,
    stdDeviation: null,
    stemh: null,
    stemv: null,
    stitchTiles: null,
    stopColor: null,
    stopOpacity: null,
    strikethroughPosition: null,
    strikethroughThickness: null,
    stroke: null,
    strokeDasharray: null,
    strokeDashoffset: null,
    strokeLinecap: null,
    strokeLinejoin: null,
    strokeMiterlimit: null,
    strokeOpacity: null,
    strokeWidth: null,
    surfaceScale: null,
    systemLanguage: null,
    tableValues: null,
    targetX: null,
    targetY: null,
    textAnchor: null,
    textDecoration: null,
    textLength: null,
    textRendering: null,
    to: null,
    transform: null,
    u1: null,
    u2: null,
    underlinePosition: null,
    underlineThickness: null,
    unicode: null,
    unicodeBidi: null,
    unicodeRange: null,
    unitsPerEm: null,
    use: null,
    vAlphabetic: null,
    vHanging: null,
    vIdeographic: null,
    vMathematical: null,
    values: null,
    version: null,
    vertAdvY: null,
    vertOriginX: null,
    vertOriginY: null,
    viewBox: null,
    viewTarget: null,
    visibility: null,
    widths: null,
    wordSpacing: null,
    writingMode: null,
    x1: null,
    x2: null,
    x: null,
    xChannelSelector: null,
    xHeight: null,
    xmlns: null,
    'xlink:actuate': null,
    'xlink:arcrole': null,
    'xlink:href': null,
    'xlink:role': null,
    'xlink:show': null,
    'xlink:title': null,
    'xlink:type': null,
    'xml:base': null,
    'xml:lang': null,
    'xml:space': null,
    y1: null,
    y2: null,
    y: null,
    yChannelSelector: null,
    z: null,
    zoomAndPan: null
}

for (let propName in DOMProperties) {

    let propConfig = DOMProperties[propName];

    let propertyInfo = {
        attributeName: propName.toLowerCase(),
        attributeNamespace: null,
        propertyName: propName,
        mutationMethod: null,

        mustUseProperty: checkMask(propConfig, MUST_USE_PROPERTY),
        hasSideEffects: checkMask(propConfig, IS_EDGE_CASE),
        hasBooleanValue: checkMask(propConfig, HAS_BOOLEAN_VALUE),
        hasNumericValue: checkMask(propConfig, HAS_NUMERIC_VALUE),
        hasPositiveNumericValue: checkMask(propConfig, HAS_POSITIVE_NUMERIC_VALUE),
    };

    if (DOMAttributeNames[propName]) {
        let attributeName = DOMAttributeNames[propName];
        propertyInfo.attributeName = attributeName;
    }

    if (DOMAttributeNamespaces[propName]) {
        propertyInfo.attributeNamespace = DOMAttributeNamespaces[propName];
    }

    if (DOMPropertyNames[propName]) {
        propertyInfo.propertyName = DOMPropertyNames[propName];
    }

    DOMPropertyContainer[propName] = propertyInfo;
}

export default DOMPropertyContainer;