const unitlessProps = {
	flex: true,
	base: true,
	zoom: true,
	order: true,
	marker: true,
	stress: true,
	volume: true,
	widows: true,
	zIndex: true,
	boxFlex: true,
	gridRow: true,
	opacity: true,
	orphans: true,
	tabSize: true,
	flexGrow: true,
	richness: true,
	flexOrder: true,
	lineClamp: true,
	msBoxFlex: true,
	flexShrink: true,
	fontWeight: true,
	gridColumn: true,
	lineHeight: true,
	pitchRange: true,
	MozBoxFlex: true,
	columnCount: true,
	stopOpacity: true,
	fillOpacity: true,
	strokeWidth: true,
	boxFlexGroup: true,
	counterReset: true,
	flexPositive: true,
	flexNegative: true,
	strokeOpacity: true,
	WebkitBoxFlex: true,
	WebkitGridRow: true,
	WebkitFlexGrow: true,
	boxOrdinalGroup: true,
	WebkitFlexShrink: true,
	counterIncrement: true,
	strokeDashoffset: true,
	WebkitStrokeWidth: true,
	MozBoxOrdinalGroup: true,
	WebkitBoxOrdinalGroup: true,
	animationIterationCount: true,
	WebkitAnimationIterationCount: true
};

export default ( str ) => {
	return str in unitlessProps;
};