import masks from "../vars/masks";

let
    MUST_USE_ATTRIBUTE = masks.MUST_USE_ATTRIBUTE,
    MUST_USE_PROPERTY = masks.MUST_USE_PROPERTY,
    HAS_SIDE_EFFECTS = masks.HAS_SIDE_EFFECTS,
    HAS_BOOLEAN_VALUE = masks.HAS_BOOLEAN_VALUE,
    HAS_NUMERIC_VALUE = masks.HAS_NUMERIC_VALUE,
    HAS_POSITIVE_NUMERIC_VALUE = masks.HAS_POSITIVE_NUMERIC_VALUE,
    HAS_OVERLOADED_BOOLEAN_VALUE = masks.HAS_OVERLOADED_BOOLEAN_VALUE;

    export default {

        allowFullScreen: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        allowTransparency: MUST_USE_ATTRIBUTE,
        async: HAS_BOOLEAN_VALUE,
        autoPlay: HAS_BOOLEAN_VALUE,
        capture: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        charSet: MUST_USE_ATTRIBUTE,
        challenge: MUST_USE_ATTRIBUTE,
        checked: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        classID: MUST_USE_ATTRIBUTE,
        className: MUST_USE_PROPERTY,
		cols: MUST_USE_ATTRIBUTE | HAS_POSITIVE_NUMERIC_VALUE,
        contextMenu: MUST_USE_ATTRIBUTE,
        controls: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        dateTime: MUST_USE_ATTRIBUTE,
        defer: HAS_BOOLEAN_VALUE,
        disabled: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        download: HAS_OVERLOADED_BOOLEAN_VALUE,
        form: MUST_USE_ATTRIBUTE,
        formAction: MUST_USE_ATTRIBUTE,
        formEncType: MUST_USE_ATTRIBUTE,
        formMethod: MUST_USE_ATTRIBUTE,
        formNoValidate: HAS_BOOLEAN_VALUE,
        formTarget: MUST_USE_ATTRIBUTE,
        frameBorder: MUST_USE_ATTRIBUTE,
        height: MUST_USE_PROPERTY,
        hidden: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        id: MUST_USE_PROPERTY,
        inputMode: MUST_USE_ATTRIBUTE,
        is: MUST_USE_ATTRIBUTE,
        keyParams: MUST_USE_ATTRIBUTE,
        keyType: MUST_USE_ATTRIBUTE,
		label: MUST_USE_PROPERTY,
        list: MUST_USE_ATTRIBUTE,
        loop: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        manifest: MUST_USE_ATTRIBUTE,
        maxLength: MUST_USE_ATTRIBUTE,
        media: MUST_USE_ATTRIBUTE,
        minLength: MUST_USE_ATTRIBUTE,
        multiple: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        muted: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        name: MUST_USE_PROPERTY,
        noValidate: HAS_BOOLEAN_VALUE,
        open: HAS_BOOLEAN_VALUE,
        placeholder: MUST_USE_PROPERTY,
		readOnly: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        required: HAS_BOOLEAN_VALUE,
        role: MUST_USE_ATTRIBUTE,
        rows: MUST_USE_ATTRIBUTE | HAS_POSITIVE_NUMERIC_VALUE,
        scoped: HAS_BOOLEAN_VALUE,
        seamless: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        selected: MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE,
        size: MUST_USE_ATTRIBUTE | HAS_POSITIVE_NUMERIC_VALUE,
        sizes: MUST_USE_ATTRIBUTE,
        span: HAS_POSITIVE_NUMERIC_VALUE,
        srcDoc: MUST_USE_PROPERTY,
        srcSet: MUST_USE_ATTRIBUTE,
        start: HAS_NUMERIC_VALUE,
        value: MUST_USE_PROPERTY | HAS_SIDE_EFFECTS,
        width: MUST_USE_PROPERTY,
        wmode: MUST_USE_ATTRIBUTE,
        itemProp: MUST_USE_ATTRIBUTE,
        itemScope: MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE,
        itemType: MUST_USE_ATTRIBUTE,
        itemID: MUST_USE_ATTRIBUTE,
        itemRef: MUST_USE_ATTRIBUTE,
        security: MUST_USE_ATTRIBUTE,
        unselectable: MUST_USE_ATTRIBUTE
    };